# Generated by Django 4.2.16 on 2024-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_interchange',
            field=models.BooleanField(default=False),
        ),
    ]
